---

name: samp-stack

networks:
  samp-net: null

volumes:
  mariadb-data:

services:
  mariadb:
    restart: always
    container_name: samp-mariadb
    image: mariadb:11.7.2
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - samp-net
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  server:
    restart: always
    container_name: samp-server
    depends_on:
      - mariadb
    image: registry.vxn.dev/open.mp/run:ubuntu-22.04
    networks:
      - samp-net
    volumes:
      - /opt/open.mp/data:/data
      - /opt/open.mp/libssl.so.1.1:/usr/lib/libssl.so.1.1
      - /opt/open.mp/libcrypto.so.1.1:/usr/lib/libcrypto.so.1.1
    ports:
      - 39876:39876/udp
      - 39876:39876/tcp


