#define UNKNOWN_CP_TYPE 	-1
#define CP_TYPE_GROUND_NORMAL 	0
#define CP_TYPE_GROUND_FINISH 	1
#define CP_TYPE_GROUND_EMPTY 	2
#define CP_TYPE_AIR_NORMAL 	3
#define CP_TYPE_AIR_FINISH 	4
#define CP_TYPE_AIR_ROTATING 	5
#define CP_TYPE_AIR_STROBING 	6
#define CP_TYPE_AIR_SWINGING 	7
#define CP_TYPE_AIR_BOBBING 	8

enum E_DRAG_RACE_ID
{
	E_DRAG_RACE_ID_NONE,
	E_DRAG_RACE_ID_LV_PYRAMID
}

new gDragRace[MAX_PLAYERS][E_DRAG_RACE_ID];

public StartDragRace()
{
	return 1;
}
