enum E_MAPICON_ID
{
	E_MAPICON_ID_SQUARE_DYNAMIC,
	E_MAPICON_ID_SQUARE,
	E_MAPICON_ID_PLAYER_POSITION,
	E_MAPICON_ID_PLAYER,
	E_MAPICON_ID_NORTH,
	E_MAPICON_ID_AIRYARD,
	E_MAPICON_ID_AMMU_NATION,
	E_MAPICON_ID_BARBER,
	E_MAPICON_ID_BIG_SMOKE,
	E_MAPICON_ID_BOAT_YARD,
	E_MAPICON_ID_BURGER_SHOT,
	E_MAPICON_ID_QUARRY,
	E_MAPICON_ID_CATALINA,
	E_MAPICON_ID_CESAR,
	E_MAPICON_ID_CLUCKIN_BELL,
	E_MAPICON_ID_CARL_JOHNSON,
	E_MAPICON_ID_CRASH,
	E_MAPICON_ID_DINER,
	E_MAPICON_ID_EMMET,
	E_MAPICON_ID_ENEMY_ATTACK,
	E_MAPICON_ID_FIRE,
	E_MAPICON_ID_GIRLFRIEND,
	E_MAPICON_ID_HOSPITAL,
	E_MAPICON_ID_LOCO,
	E_MAPICON_ID_MADD_DOGG,
	E_MAPICON_ID_CALIGULA,
	E_MAPICON_ID_MC_STRAP,
	E_MAPICON_ID_MOD_GARAGE,
	E_MAPICON_ID_OG_LOC,
	E_MAPICON_ID_PIZZA,
	E_MAPICON_ID_POLICE,
	E_MAPICON_ID_PROPERTY_FOR_SALE,
	E_MAPICON_ID_PROPERTY_NOT_FOR_SALE,
	E_MAPICON_ID_RACE,
	E_MAPICON_ID_RYDER,
	E_MAPICON_ID_SAVE_HOUSE,
	E_MAPICON_ID_SCHOOL,
	E_MAPICON_ID_MYSTERY,
	E_MAPICON_ID_SWEET,
	E_MAPICON_ID_TATTOO,
	E_MAPICON_ID_TRUTH,
	E_MAPICON_ID_WAYPOINT,
	E_MAPICON_ID_TORENO_RANCH,
	E_MAPICON_ID_TRIADS,
	E_MAPICON_ID_TRIADS_CASINO,
	E_MAPICON_ID_CLOTHES,
	E_MAPICON_ID_WOOZIE,
	E_MAPICON_ID_ZERO,
	E_MAPICON_ID_DISCO,
	E_MAPICON_ID_DRINK,
	E_MAPICON_ID_RESTAURANT,
	E_MAPICON_ID_TRUCKING,
	E_MAPICON_ID_ROBBERY,
	E_MAPICON_ID_RACE_TOURNAMENT,
	E_MAPICON_ID_GYM,
	E_MAPICON_ID_CAR_IMPOUND,
	E_MAPICON_ID_LIGHT,
	E_MAPICON_ID_AIR_STRIP,
	E_MAPICON_ID_VARRIOS_LOS_AZTECAS,
	E_MAPICON_ID_BALLAS,
	E_MAPICON_ID_LOS_SANTOS_VAGOS,
	E_MAPICON_ID_SA_FIERRO_RIFA,
	E_MAPICON_ID_GROVE_STREET,
	E_MAPICON_ID_PAY_N_SPRAY
}

public AddMapicons(playerid)
{
	// The very global spawn point in LV.
	SetPlayerMapIcon(playerid, 0, 2323.73, 1283.18, 97.60, E_MAPICON_ID_ENEMY_ATTACK, 0, MAPICON_LOCAL);

	// ATMs.
	for (new i = 0; i < sizeof(gBankLocation); i++)
	{
		SetPlayerMapIcon(playerid, i+1, Float:gBankLocation[i][0], Float:gBankLocation[i][1], Float:gBankLocation[i][2], E_MAPICON_ID_ROBBERY, 0, MAPICON_LOCAL);
	}

	// Housing.
	SetPlayerMapIcon(playerid, 20, 1442.6, -637.3, 95.1, E_MAPICON_ID_PROPERTY_NOT_FOR_SALE, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 21, 541.0, 2364.8, 31.2, E_MAPICON_ID_PROPERTY_NOT_FOR_SALE, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 22, -2657.27, 882.27, 79.34, E_MAPICON_ID_PROPERTY_NOT_FOR_SALE, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 23, -2686.03, 205.63, 3.96, E_MAPICON_ID_PROPERTY_NOT_FOR_SALE, 0, MAPICON_LOCAL);

	SetPlayerMapIcon(playerid, 23, -1497.76, 2671.87, 55.25, E_MAPICON_ID_PROPERTY_FOR_SALE, 0, MAPICON_LOCAL);

	// Jobs.
	SetPlayerMapIcon(playerid, 40, 970.7, 2155.0, 10.8, E_MAPICON_ID_TRUCKING, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 41, 2287.1, 2426.7, 10.8, E_MAPICON_ID_POLICE, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 42, -91.76, -305.44, 1.42, E_MAPICON_ID_TRUCKING, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 43, -81.32, -1135.79, 0.91, E_MAPICON_ID_TRUCKING, 0, MAPICON_LOCAL);

	// Oznaceni zavodist + stanovist tymu Dragsteru.
	SetPlayerMapIcon(playerid, 50, 2620.14, 1195.76, 10.81, E_MAPICON_ID_RACE_TOURNAMENT, 0, MAPICON_LOCAL);
	SetPlayerMapIcon(playerid, 51, 1882.48, -2419.96, 13.11, E_MAPICON_ID_RACE_TOURNAMENT, 0, MAPICON_LOCAL);

	// Airports.
	SetPlayerMapIcon(playerid, 60, 414.3, 2528.1, 16.6, E_MAPICON_ID_AIRYARD, 0, MAPICON_LOCAL);
}
